### PR TITLE
Pull 4

### PR DESCRIPTION
**Pull request by JonathanMerritt**
I Edited/Removed/Added many files, you'll have to look through it for all the changes.

I have not added any documentation yet, but I will do it soon.

I would suggest that you look at adding some kind of database and/backend API for different theaters etc... Also some sort of session like system for users to keep track of ticket buys and all that goes along with it.

The way I handle data binding and view models and lifecycles is different than how Google is now doing it.
I would say that you look over both methods and decide for yourself.

And Rx Java would be a massive improvement, I'm sorry I didn't have the time to integrate it.

Please let me know if you want to talk about anything going on with the code. Before or after I document it.

I'll also edit the readme if you want. Considering that some things are no longer relevant.

### CODE REVIEW

**Comment by tranngoclam** [comment]
I'm checking, pls wait 👍

**Comment by tranngoclam** [comment]
Dear @JonathanMerritt 

Thanks for your great contribution in this PR. It's a big change, I'd like to suggest some ways to continue with this repo.
* Backend/API: we can use `mockwebserver` of Retrofit library instead of a real server to handle api request
* RxJava: it's nice for usage, if you decide to use it, please go with RxJava2
* Unit test: we should separate login from `presentation layer` into smaller parts, such as `data layer` and `domain layer` for easily to test them

I'm very happy about your contribution and your knowledge about new trending technology in Android. Currently I'm too busy with my company's projects, but I'm going to start a new open source called `Reactive Components Architecture` based on `Architecture Components` (Google) and RxJava. I'll add you as a contribution for this project.

Thank you so much

**Comment by JonathanMerritt** [comment]
@tranngoclam

I'm happy to help out. As for you suggestions.

- A backend is certainly needed, I don't have a huge amount of experience with it, however I do know how to use Retrofit and have setup a few things with it. I will have a look at figuring this out for this project.

- RxJava2 is what I meant. I'll also add it in, it will become almost necessary with Retrofit anyway.

- I have zero experience or knowledge in testing whatsoever. I understand it's importance and respect it, I simply just haven't had the time to learn both testing and basic development. I'll always defer to you for anything testing. Adding a domain layer however is something I was planning to add as well.


Again, happy to help and happy to be of help. 

Your next project sounds good. When Google opened up all their ViewModel stuff it honestly threw a bit of a roadblock in front of me. I've been working on the system I use in this project for a while, but it's almost exactly the opposite of what they are doing. I even changed the name to Controller to differentiate it.

They are creating and storing ViewModels, that then has its data wrapped and wholely observed. I'm​ creating and re creating them and each one breaks the data down into specific values that are then observed. 

They hook into the activity/fragment lifecycles different as well. 

I was thinking I was doing things right and then blam, now I'm questioning everything.

That's my excuse as to why this pull was slightly unfinished. 

I may add some documentation later, as well as update the README. If that's ok?

There are also things I don't like with how I'm doing it.

- Too many checks, also too many iterations. I believe RxJava2 will improve this in some ways.

- The SeatChanger seems like a cheat to me, I'm not sure if Dagger should be leveraged in this way or not.

- Other I can't remember...

**Comment by JonathanMerritt** [comment]
@tranngoclam 

Unfortunately I am at a complete standstill. Can't seem to get past the things I don't like, plus a bit confused on the things that need to be added.

Aside from updating the Readme, I will be happy to take any pointers or advice as to what to tackle first. I know you said you don't have much time, that's totally fine. Just wanted to let you know, that I may not make much progress on this for a little while... At least till I pass this road block.

**Pull request merged**
